version: "3.8"

services:
  mysql:
    image: mysql:8.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=plura
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql/:rw
    ports:
      - "3306:3306"
    user: "1000:1000"
